image:
  file: .gitpod.Dockerfile

tasks:
  - name: Prepare
    init: |
      time nix-shell --run "exit 0"
      direnv allow
      gp sync-done nix-setup
      exit 0

  - name: tailscaled
    command: |
      # Wait for nix to have initialized the environmnet
      gp sync-await nix-setup
      # Start tailscale daemon
      sudo tailscaled

  - name: Shell
    command: |
      # TODO: https://direnv.net/
      gp sync-await nix-setup
      # Connecto to the tailscale network
      sudo tailscale up \
        --authkey "${TAILSCALE_AUTH_KEY}" \
        --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
        --ssh

vscode:
  extensions:
    - bbenoist.Nix
    - bungcip.better-toml
    # Disabled for now as it is kind of slow
    # - arrterian.nix-env-selector
