image:
  file: .gitpod.Dockerfile
tasks:
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      # Connecto to the tailscale network
      sudo tailscale up \
        --authkey "${TAILSCALE_AUTH_KEY}" \
        --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
        --ssh
