image:
  file: .gitpod.Dockerfile

tasks:
  - name: tailscaled
    command: |
      # Wait for nix to have initialized the environmnet
      gp sync-await nix-setup
      # Start tailscale daemon
      nix-shell --run 'sudo $(which tailscaled)'
      
  - name: Prepare
    command: |
      # This ensures we populate the Nix store with all the packages needed by shell.nix
      time nix-shell --run "exit 0"
      gp sync-done nix-setup

      echo "Connecting to tailscale network"
      nix-shell --run 'sudo $(which tailscale) up \
        --authkey "${TAILSCALE_AUTH_KEY}" \
        --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
        --ssh'
      
      echo "Setup ready :-)"
      nix-shell

vscode:
  extensions:
    - bbenoist.Nix
    - bungcip.better-toml
    # Disabled for now as it is kind of slow
    # - arrterian.nix-env-selector
