image: ubuntu:22.04

tasks:
     
  - name: tailscaled
    command: |
      # Wait for nix to have initialized the environmnet
      gp sync-await nix-setup
      # Start tailscale daemon
      sudo tailscaled

  - name: Shell
    command: |
      # TODO: https://direnv.net/
      direnv allow

      # Configure nix. We don't need sandboxing
      # https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-sandbox
      mkdir -p /home/gitpod/.config/nix
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf
      
      gp sync-done nix-setup

      # Connecto to the tailscale network
      sudo tailscale up \
        --authkey "${TAILSCALE_AUTH_KEY}" \
        --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
        --ssh

vscode:
  extensions:
    - bbenoist.Nix
    - bungcip.better-toml
